### ISSUE TITLE
issue when statsd is disabled

### ISSUE THREAD

**Issue by nicolasricci** [SoCloz/SoclozMonitoringBundle#10]
Hi,

statsd is currently mandatory on the 1.1.1 branch. 

Fatal Error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 2 passed to Socloz\MonitoringBundle\Listener\Exceptions::__construct() must be an instance of Socloz\MonitoringBundle\Notify\StatsD\StatsDInterface, null given

This dependency should be removed in the Exceptions constructor.

**Comment by mhor** [comment]
@nicolasricci could you check if [this PR](https://github.com/SoCloz/SoclozMonitoringBundle/pull/11) solve your problem

**Comment by nicolasricci** [comment]
@mhor yes it does fix the issue thanks. you can merge the PR.

**Comment by mhor** [comment]
Thanks for your feedback @nicolasricci
